server: 
   port: 8282
   
   
spring: 
   application: 
      name: dubbo-consumer
      
      
dubbo: 
   application:
#      name: dubbo-consumer
   protocol:
      name: dubbo
      port: -1
   scan: 
      base-packages: com.yzl.study.spingboot
   registry:
      address: nacos://192.168.1.3:8848
   consumer:
      check: false
   config-center: 
      address: nacos://192.168.1.3:8848


nacos: 
   config: 
      serverAddr: 192.168.1.3:8848
      namespace: f78a2b0f-4abd-4a36-be93-ac334aa2fbbc

   discovery: 
      server-addr: 192.168.1.3:8848



demo: 
   service: 
      version: 1.0.0
      
nacosDataId: testDataId       
      