server:
   port: 8080

spring: 
   application: 
      name: dubbo-provider
      
      
      
      
dubbo: 
   application: 
#      name: ${spring.application.name}  # The default value of dubbo.application.name is ${spring.application.name}
   protocol: 
      name: dubbo
      port: -1
   registry: 
      address: nacos://192.168.1.3:8848
   scan: 
      base-packages: com.yzl.study.spingboot
   config-center: 
      address: nacos://192.168.1.3:8848

nacos: 
   config: 
      serverAddr: 192.168.1.3:8848
      namespace: f78a2b0f-4abd-4a36-be93-ac334aa2fbbc

   discovery: 
      server-addr: 192.168.1.3:8848


nacosDataId: testDataId


## DemoService version
demo: 
   service: 
      version: 1.0.0
      
      
      
      